services:
  - type: web
    name: Gravity Check Box
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: 3.10.12
